### ISSUE TITLE
Ignore function evaluations that return Inf (or NaN)

### ISSUE THREAD

**Issue by pcjentsch** [JuliaApproxInference/KissABC.jl#19]
When I train ODE models, some parameter combinations tend to cause the solution to be too stiff, which causes the solver to exit early and return an error.

Usually, when this happens I return a cost of `Inf` and which regular parameter optimization, the solution is ignored. 

However, for some of the Bayesian parameter estimation algorithms that value is kept and it seems to prevent the algorithm from converging (`range_\epsilon` = (x, Inf)` for instance). 

Would it be possible to add a mode that just discards that point?

Thank you

**Comment by francescoalemanno** [comment]
i'm working on a PR that could fix this issue, can you try the branch `fix19` on your problems to see if it helps?

**Comment by pcjentsch** [comment]
The fix seems to work, thanks I appreciate it. I am still using v1.3.0 for my research at the moment as it seems to give better performance. Increasing the burnin as you mentioned in the forum does help, but it takes much longer to get similarly tight posterior distributions in my problem with v2.0. I have around 17 variables at the moment, though, so many there is another parameter I should tweak?
